spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/[/database]?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username:
    password:
    initialization-mode : always

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    defer-datasource-initialization : true